#!/usr/bin/env python3
"""Deterministically compose every paper result macro from archived outputs."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any, Iterable

import yaml


ARTIFACT_ROOT = Path(__file__).resolve().parents[1]


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def one(rows: Iterable[dict[str, str]], **selectors: object) -> dict[str, str]:
    matches = [
        row
        for row in rows
        if all(_selector_equal(row.get(key), value) for key, value in selectors.items())
    ]
    if len(matches) != 1:
        raise ValueError(f"expected one row for {selectors}, found {len(matches)}")
    return matches[0]


def _selector_equal(actual: str | None, expected: object) -> bool:
    if isinstance(expected, float):
        try:
            return abs(float(actual or "nan") - expected) < 1e-12
        except ValueError:
            return False
    return actual == str(expected)


def f4(value: object) -> str:
    return f"{float(value):.4f}"


def f6(value: object) -> str:
    return f"{float(value):.6f}"


def integer(value: object) -> str:
    return str(int(float(value)))


def grouped_integer(value: object) -> str:
    return f"{int(float(value)):,}"


def percent1(value: object) -> str:
    return f"{100.0 * float(value):.1f}\\%"


def macro(name: str, value: object) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def render(default_results: Path, llm_results: Path) -> str:
    summary = read_json(default_results / "summary.json")
    oracle = read_json(default_results / "data/oracle/oracle.json")
    methods = read_csv(default_results / "metrics/method_metrics.csv")
    robustness = read_csv(default_results / "metrics/robustness_aggregate.csv")
    statistics = read_csv(default_results / "metrics/statistics.csv")
    leave_one_out = read_csv(default_results / "metrics/leave_one_source_out.csv")
    config = yaml.safe_load(
        (default_results / "config.snapshot.yaml").read_text(encoding="utf-8")
    )
    llm = read_json(llm_results / "summary.json")

    if not isinstance(config, dict):
        raise ValueError("config.snapshot.yaml must contain a mapping")
    cigma = summary["cigma"]
    benchmark = summary["benchmark"]
    robust_design = summary["robustness"]
    cigma_row = one(methods, method="cigma")
    cigma_details = read_json(default_results / "evaluation/cigma.json")
    calibration_rows = cigma_details.get("edge_rows")
    if not isinstance(calibration_rows, list) or not all(
        isinstance(row, dict) and row.get("label") in (0, 1)
        for row in calibration_rows
    ):
        raise ValueError("CIGMA calibration rows must have binary integer labels")
    calibration_cases = len(calibration_rows)
    calibration_positives = sum(int(row["label"]) for row in calibration_rows)
    tabulated_cases = round(float(cigma_row["edge_calibration_cases"]))
    tabulated_fraction = float(cigma_row["edge_calibration_positive_fraction"])
    if calibration_cases != tabulated_cases:
        raise ValueError("CIGMA calibration case count disagrees with evaluation rows")
    if calibration_cases and abs(
        calibration_positives / calibration_cases - tabulated_fraction
    ) > 5e-10:
        raise ValueError("CIGMA calibration fraction disagrees with evaluation rows")
    critical_targets = sum(
        bool(node.get("migration_target")) and int(node.get("priority", 0)) >= 2
        for node in oracle["nodes"]
    )

    lines = [
        "% Auto-generated by artifact/scripts/export_paper_macros.py; do not edit.",
        "% Values are derived only from archived default and LLM result files.",
        macro("CigmaEntityObs", integer(benchmark["public_entity_observations"])),
        macro("CigmaClaimObs", integer(benchmark["public_claim_observations"])),
        macro("CigmaAssetFOne", f4(cigma["asset_f1"])),
        macro("CigmaEntityFOne", f4(cigma["entity_f1"])),
        macro("CigmaBThreeFOne", f4(cigma["b3_f1"])),
        macro("CigmaEdgePrecision", f4(cigma_row["edge_precision"])),
        macro("CigmaEdgeRecall", f4(cigma_row["edge_recall"])),
        macro("CigmaEdgeFOne", f4(cigma["edge_f1"])),
        macro("CigmaNDCGFive", f4(cigma["ndcg_at_5"])),
        macro("CigmaNDCGTen", f4(cigma["ndcg_at_10"])),
        macro("CigmaKendallTauB", f4(cigma["kendall_tau_b"])),
        macro("CigmaUnsupportedRate", f4(cigma["unsupported_edge_rate"])),
        macro("CigmaCriticalMisses", integer(cigma["critical_misses"])),
        macro("CigmaCriticalTargets", critical_targets),
        macro("CigmaVerificationQueue", integer(cigma["verification_queue_size"])),
        macro("CigmaEdgeBrier", f6(cigma["edge_brier"])),
        macro("CigmaEdgeECE", f6(cigma["edge_ece"])),
        macro("CigmaUrgencyBrier", f6(cigma["urgency_brier"])),
        macro("CigmaUrgencyECE", f6(cigma["urgency_ece"])),
        macro("CigmaCalibrationCases", calibration_cases),
        macro("CigmaCalibrationPositives", calibration_positives),
        macro("CigmaPerturbationSeeds", integer(robust_design["seeded_perturbations"])),
        macro("CigmaRobustnessRuns", integer(robust_design["total_runs"])),
        macro("BootstrapResamples", grouped_integer(config["evaluation"]["bootstrap_resamples"])),
        macro("PermutationDraws", grouped_integer(config["evaluation"]["permutations"])),
        "",
        "% Three frozen Responses API repetitions evaluated only after generation.",
    ]

    llm_means = llm["means"]
    base_precision = (
        llm["base_true_positive_edges"] / llm["base_predicted_edges"]
        if llm["base_predicted_edges"]
        else 0.0
    )
    base_recall = llm["base_recall"]
    base_f1 = (
        2.0 * base_precision * base_recall / (base_precision + base_recall)
        if base_precision + base_recall
        else 0.0
    )
    lines.extend(
        [
            macro("LLMRuns", integer(llm["runs"])),
            macro("LLMBasePrecision", f4(base_precision)),
            macro("LLMBaseRecall", f4(base_recall)),
            macro("LLMBaseFOne", f4(base_f1)),
            macro("LLMRawPrecision", f4(llm_means["raw_precision"])),
            macro("LLMRawRecall", f4(llm_means["raw_recall"])),
            macro("LLMRawFOne", f4(llm_means["raw_f1"])),
            macro("LLMValidatedPrecision", f4(llm_means["accepted_precision"])),
            macro("LLMValidatedRecall", f4(llm_means["accepted_recall"])),
            macro("LLMValidatedFOne", f4(llm_means["accepted_f1"])),
            macro("LLMHybridPrecision", f4(llm_means["hybrid_precision"])),
            macro("LLMHybridRecall", f4(llm_means["hybrid_recall"])),
            macro("LLMHybridFOne", f4(llm_means["hybrid_f1"])),
            macro("LLMValidatorRejection", percent1(llm_means["validator_rejection_rate"])),
            macro("LLMRawFalseTripleRate", percent1(llm_means["raw_false_triple_rate"])),
            macro(
                "LLMAcceptedFalseTripleRate",
                percent1(llm_means["accepted_false_triple_rate"]),
            ),
            macro("LLMIncrementalRecall", f4(llm_means["incremental_edge_recall"])),
            macro("LLMAcceptedJaccard", f4(llm["pairwise_accepted_jaccard_mean"])),
            macro("LLMInputTokens", grouped_integer(llm["aggregate_usage"]["input_tokens"])),
            macro("LLMOutputTokens", grouped_integer(llm["aggregate_usage"]["output_tokens"])),
            "",
            "% Complete-fixture methods.",
        ]
    )

    for method_name, prefix in [
        ("tls_inventory", "TLS"),
        ("cbom_inventory", "CBOM"),
        ("source_union", "Union"),
        ("exact_direct", "Exact"),
    ]:
        row = one(methods, method=method_name)
        lines.extend(
            [
                macro(f"{prefix}AssetFOne", f4(row["asset_f1"])),
                macro(f"{prefix}EdgePrecision", f4(row["edge_precision"])),
                macro(f"{prefix}EdgeRecall", f4(row["edge_recall"])),
                macro(f"{prefix}EntityFOne", f4(row["entity_f1"])),
                macro(f"{prefix}BThreeFOne", f4(row["b3_f1"])),
                macro(f"{prefix}EdgeFOne", f4(row["edge_f1"])),
                macro(f"{prefix}UnsupportedRate", f4(row["unsupported_edge_rate"])),
                macro(f"{prefix}CriticalMisses", integer(row["critical_misses"])),
            ]
        )

    lines.extend(["", "% CIGMA ablations."])
    for method_name, prefix in [
        ("cigma_no_alias", "NoAlias"),
        ("cigma_no_paths", "NoPaths"),
        ("cigma_no_quality_gate", "NoGate"),
        ("cigma_uniform_reliability", "Uniform"),
    ]:
        row = one(methods, method=method_name)
        lines.extend(
            [
                macro(f"{prefix}AssetFOne", f4(row["asset_f1"])),
                macro(f"{prefix}EdgeFOne", f4(row["edge_f1"])),
                macro(f"{prefix}UnsupportedRate", f4(row["unsupported_edge_rate"])),
                macro(f"{prefix}Verify", integer(row["verification_queue_size"])),
                macro(f"{prefix}NDCGTen", f4(row["ndcg_at_10_primary"])),
                macro(f"{prefix}EdgeBrier", f6(row["edge_brier"])),
                macro(f"{prefix}EdgeECE", f6(row["edge_ece"])),
            ]
        )

    lines.extend(
        [
            "",
            "% Alternative ordering rules on the complete CIGMA graph.",
            macro("WeightedNDCGFive", f4(cigma_row["ndcg_at_5_weighted"])),
            macro("WeightedNDCGTen", f4(cigma_row["ndcg_at_10_weighted"])),
            macro("WeightedKendallTauB", f4(cigma_row["kendall_tau_b_weighted"])),
            macro("RankAggNDCGFive", f4(cigma_row["ndcg_at_5_rank_aggregation"])),
            macro("RankAggNDCGTen", f4(cigma_row["ndcg_at_10_rank_aggregation"])),
            macro("RankAggKendallTauB", f4(cigma_row["kendall_tau_b_rank_aggregation"])),
            "",
            "% CIGMA robustness means and percentile bootstrap intervals.",
        ]
    )

    dropout_specs = [
        (0.10, "DropTen"),
        (0.25, "DropTwentyFive"),
        (0.50, "DropFifty"),
    ]
    for dropout, prefix in dropout_specs:
        asset = one(
            robustness,
            method="cigma",
            observation_dropout=dropout,
            metric="asset_f1",
        )
        edge = one(
            robustness,
            method="cigma",
            observation_dropout=dropout,
            metric="edge_f1",
        )
        ndcg5 = one(
            robustness,
            method="cigma",
            observation_dropout=dropout,
            metric="ndcg_at_5_primary",
        )
        ndcg10 = one(
            robustness,
            method="cigma",
            observation_dropout=dropout,
            metric="ndcg_at_10_primary",
        )
        critical = one(
            robustness,
            method="cigma",
            observation_dropout=dropout,
            metric="critical_miss_rate",
        )
        lines.extend(
            [
                macro(f"{prefix}AssetMean", f4(asset["mean"])),
                macro(f"{prefix}AssetLow", f4(asset["ci95_low"])),
                macro(f"{prefix}AssetHigh", f4(asset["ci95_high"])),
                macro(f"{prefix}EdgeMean", f4(edge["mean"])),
                macro(f"{prefix}EdgeLow", f4(edge["ci95_low"])),
                macro(f"{prefix}EdgeHigh", f4(edge["ci95_high"])),
            ]
        )
        if dropout == 0.50:
            lines.append(macro(f"{prefix}NDCGFive", f4(ndcg5["mean"])))
        lines.extend(
            [
                macro(f"{prefix}NDCGTen", f4(ndcg10["mean"])),
                macro(f"{prefix}CriticalMissRate", f4(critical["mean"])),
            ]
        )

    for metric, suffix in [
        ("asset_f1", "AssetDifference"),
        ("edge_f1", "EdgeDifference"),
        ("ndcg_primary", "NDCGDifference"),
    ]:
        row = one(
            statistics,
            analysis="paired_cigma_difference",
            baseline="exact_direct",
            method="cigma",
            metric=metric,
            observation_dropout=0.50,
        )
        lines.append(macro(f"DropFifty{suffix}", f4(row["mean_difference"])))

    lines.extend(["", "% Leave-one-source-out extrema discussed in the text."])
    without_code = one(leave_one_out, dropped_source="code")
    without_cmdb = one(leave_one_out, dropped_source="cmdb")
    without_tls = one(leave_one_out, dropped_source="tls")
    lines.extend(
        [
            macro("WithoutCodeAssetFOne", f4(without_code["asset_f1"])),
            macro("WithoutCodeCriticalMisses", integer(without_code["critical_misses"])),
            macro("WithoutCMDBCriticalMisses", integer(without_cmdb["critical_misses"])),
            macro("WithoutTLSNDCGTen", f4(without_tls["ndcg_at_10_primary"])),
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--default-results",
        type=Path,
        default=ARTIFACT_ROOT / "results/default",
    )
    parser.add_argument(
        "--llm-results",
        type=Path,
        default=ARTIFACT_ROOT / "results/llm/evaluation",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ARTIFACT_ROOT.parent / "paper/results_macros.tex",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the rendered bytes with --output instead of writing",
    )
    args = parser.parse_args()
    rendered = render(args.default_results, args.llm_results)
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"paper macros are stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
